services:
  # Servicio de la API NestJS
  app:
    build:
      context: .
      target: development 
    container_name: restaurant_api
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run start:dev 
    depends_on:
      - db
      - redis
    networks:
      - restaurant_network

  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    ports:
      - "${DB_PORT:-5432}:5432" 
    environment:
      POSTGRES_USER: ${DB_USER:-testuser}     
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test} 
      POSTGRES_DB: ${DB_NAME:-restaurant_orders_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant_network

  # Servicio de Caché Redis
  redis:
    image: redis:7-alpine
    container_name: restaurant_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - restaurant_network

volumes:
  postgres_data:

networks:
  restaurant_network:
    driver: bridge